"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { OnboardingFlow } from "@/features/onboarding/OnboardingFlow";
import { DEFAULT_UNIT_PREFERENCES, formatDistance, formatTemperature, readUnitPreferences } from "@/lib/preferences/units";

type Lang = "en" | "ko" | "ja" | "zh";
type Kind = "swim" | "surf" | "sup" | "kayak" | "yacht" | "walk" | "fishing";
type Category = "all" | "activity" | "fishing" | "relax" | "kids";
type OriginId = "gwangalli" | "haeundae" | "seomyeon" | "busanStation" | "nampo" | "gijang";
type TravelMode = "transit" | "car" | "walk";
export type LegacyView = "home" | "places" | "recommend";
type Localized = Record<Lang, string>;
type Spot = {
  id:string; name:Localized; activity:Localized; kind:Kind; categories:Exclude<Category,"all">[]; icon:string;
  lat:number; lon:number; distance:number; water:number; wave:number; wind:number;
  temp:number; rain:number; crowd:number; group:[number,number];
};

const ui = {
  en:{title:"Compare every coast.",accent:"Pick the best one now.",sub:"We rank Busan’s beaches using local weather, sea conditions, estimated crowds, distance and group size.",group:"Group size",goal:"What are you looking for?",all:"All",activity:"Activities",fishing:"Fishing",relax:"Take it easy",kids:"With kids",live:"LIVE COMPARISON",updated:"Updated",refresh:"Refresh data",loading:"Updating…",best:"Best match now",why:"3 reasons it ranks first",condition:"Conditions",weather:"Weather",sea:"Sea",crowd:"Crowd",distance:"Distance",groupFit:"Group fit",water:"Water",wave:"Waves",wind:"Wind",rain:"Rain",people:"people",estimated:"estimated",route:"Directions",details:"See 3 reasons",results:"Top 3 recommendations",compare:"Best places for your selected travel style",otherResults:"More activities you can still enjoy",otherCompare:"Not in today’s top 3, but available across Busan",available:"Available",safe:"Good",caution:"Caution",dataLive:"Weather & marine forecast live",dataFallback:"Using backup conditions",crowdNote:"Crowding is an estimate based on location, day and time—not a live headcount.",source:"Marine forecast: Open-Meteo · weather: Open-Meteo",recommend:"Your preferred travel style is applied first, then today’s waves, weather, crowds, distance and group size are compared.",name:"BUSAN BLUE"},
  ko:{title:"부산 바다를 모두 비교해,",accent:"지금 가장 좋은 곳을 골라드려요.",sub:"해변별 날씨와 수온·파도·바람, 예상 혼잡도, 거리, 인원까지 같은 기준으로 계산해 추천합니다.",group:"함께 가는 인원",goal:"원하는 활동",all:"전체",activity:"액티비티",fishing:"낚시",relax:"편안하게",kids:"아이와 함께",live:"실시간 비교 추천",updated:"업데이트",refresh:"데이터 새로고침",loading:"불러오는 중…",best:"지금 가장 추천해요",why:"1순위로 추천하는 3가지 이유",condition:"현장 조건",weather:"날씨",sea:"바다",crowd:"혼잡도",distance:"거리",groupFit:"인원 적합",water:"수온",wave:"파도",wind:"바람",rain:"강수",people:"명",estimated:"예상",route:"길찾기",details:"추천 근거 3가지",results:"오늘의 추천 TOP 3",compare:"선택한 여행 방식에 가장 잘 맞는 장소예요",otherResults:"그 밖에 즐길 수 있는 활동",otherCompare:"오늘 TOP 3는 아니지만 부산에서 이용할 수 있어요",available:"이용 가능",safe:"좋음",caution:"주의",dataLive:"날씨·해양예보 실시간 반영",dataFallback:"기준 데이터로 계산 중",crowdNote:"혼잡도는 위치·요일·시간대 기준 예상치이며, 실제 현장 인원 집계가 아닙니다.",source:"해양예보: Open-Meteo · 날씨: Open-Meteo",recommend:"선택한 여행 방식을 가장 먼저 반영한 뒤 오늘의 파도와 날씨, 혼잡도, 거리, 인원을 비교했어요.",name:"BUSAN BLUE"},
  ja:{title:"釜山の海をまとめて比べて、",accent:"今いちばん楽しめる場所へ。",sub:"ビーチごとの天気、水温、波、風、予想混雑度、距離、人数を同じ基準で採点します。",group:"ご利用人数",goal:"過ごし方を選ぶ",all:"すべて",activity:"アクティビティ",fishing:"釣り",relax:"のんびり",kids:"子どもと一緒",live:"リアルタイム比較",updated:"更新",refresh:"データを更新",loading:"更新中…",best:"今いちばんのおすすめ",why:"1位に選んだ3つの理由",condition:"現地の状況",weather:"天気",sea:"海況",crowd:"混雑度",distance:"距離",groupFit:"人数",water:"水温",wave:"波の高さ",wind:"風速",rain:"降水",people:"人",estimated:"予想",route:"ルートを見る",details:"3つの理由を見る",results:"今日のおすすめTOP 3",compare:"選んだ過ごし方に最も合う場所",otherResults:"ほかに楽しめるアクティビティ",otherCompare:"今日のTOP 3以外にも、釜山で体験できます",available:"利用可能",safe:"良好",caution:"注意",dataLive:"天気・海洋予報を反映中",dataFallback:"基準データで計算中",crowdNote:"混雑度は場所・曜日・時間帯から算出した予想値で、実際の人数ではありません。",source:"海洋予報：Open-Meteo · 天気：Open-Meteo",recommend:"選んだ過ごし方を最優先に、今日の波・天気・混雑度・距離・人数を比較しました。",name:"BUSAN BLUE"},
  zh:{title:"对比釜山各处海岸，",accent:"找到此刻最值得去的地方。",sub:"采用统一标准，综合比较天气、水温、浪高、风速、预计拥挤度、距离及同行人数。",group:"同行人数",goal:"选择出游方式",all:"全部",activity:"水上活动",fishing:"钓鱼",relax:"轻松休闲",kids:"亲子出游",live:"实时对比推荐",updated:"更新时间",refresh:"刷新数据",loading:"更新中…",best:"此刻首选推荐",why:"推荐为第一名的3个理由",condition:"现场条件",weather:"天气",sea:"海况",crowd:"拥挤度",distance:"距离",groupFit:"人数匹配",water:"水温",wave:"浪高",wind:"风速",rain:"降水",people:"人",estimated:"预计",route:"查看路线",details:"查看3个推荐理由",results:"今日推荐TOP 3",compare:"最符合所选出游方式的地点",otherResults:"其他可体验的活动",otherCompare:"虽然未进入今日TOP 3，但仍可在釜山体验",available:"可体验",safe:"良好",caution:"注意",dataLive:"已接入天气与海洋预报",dataFallback:"正在使用备用数据",crowdNote:"拥挤度根据地点、星期和时段估算，并非现场实时人数。",source:"海洋预报：Open-Meteo · 天气：Open-Meteo",recommend:"优先匹配所选出游方式，再比较今天的浪况、天气、拥挤度、距离和同行人数。",name:"BUSAN BLUE"}
} as const;

const L=(en:string,ko:string,ja:string,zh:string):Localized=>({en,ko,ja,zh});
const locationUi={
  en:{origin:"Starting point",choose:"Choose an area",device:"Use device location",locating:"Finding your location…",located:"Device location selected",denied:"Location unavailable — using selected area",straight:"straight-line"},
  ko:{origin:"출발 지역",choose:"지역을 선택하세요",device:"현재 기기 위치 사용",locating:"현재 위치 확인 중…",located:"현재 기기 위치로 설정했어요",denied:"위치를 확인하지 못해 선택 지역을 유지해요",straight:"직선거리"},
  ja:{origin:"出発エリア",choose:"エリアを選択",device:"端末の現在地を使う",locating:"現在地を確認中…",located:"端末の現在地を設定しました",denied:"現在地を取得できないため、選択中のエリアを使います",straight:"直線距離"},
  zh:{origin:"出发区域",choose:"请选择区域",device:"使用设备当前位置",locating:"正在获取当前位置…",located:"已设为设备当前位置",denied:"无法获取当前位置，将继续使用所选区域",straight:"直线距离"},
} as const;
const directionsUi={
  en:{eyebrow:"GETTING THERE",title:"How to reach",from:"From",transit:"Public transit",car:"Car",walk:"Walk",estimate:"Estimated",distance:"Route distance",flow:"Suggested travel flow",open:"See the detailed route in Naver Map",notice:"Times and route distances are estimates based on straight-line distance. Check live traffic, bus arrivals and the final route in Naver Map before leaving.",transitSteps:["Walk to the nearest bus or subway stop","Ride toward the destination and transfer if needed","Walk from the final stop to the activity area"],carSteps:["Start navigation from your selected location","Follow the fastest road route shown in navigation","Check parking near the activity area before arrival"],walkSteps:["Follow pedestrian roads and marked crossings","Use coastal paths only where pedestrian access is open","Recheck the route if weather or access restrictions change"]},
  ko:{eyebrow:"가는 방법",title:"찾아가는 길",from:"출발",transit:"대중교통",car:"차량",walk:"도보",estimate:"예상 소요시간",distance:"예상 이동거리",flow:"예상 이동 흐름",open:"네이버 지도에서 상세 경로 확인",notice:"시간과 이동거리는 직선거리를 바탕으로 계산한 예상치입니다. 출발 전 네이버 지도에서 실시간 교통, 버스 도착 정보와 최종 경로를 확인하세요.",transitSteps:["가까운 버스 정류장 또는 도시철도역까지 이동","목적지 방향 노선을 이용하고 필요하면 환승","마지막 정류장에서 활동 장소까지 도보 이동"],carSteps:["선택한 출발지에서 차량 길찾기 시작","내비게이션이 안내하는 빠른 도로 경로 이용","도착 전 활동 장소 주변 주차 가능 여부 확인"],walkSteps:["보행자 도로와 횡단보도를 따라 이동","보행이 허용된 해안 산책로만 이용","날씨나 출입 통제 시 경로를 다시 확인"]},
  ja:{eyebrow:"アクセス",title:"行き方を見る",from:"出発地",transit:"公共交通",car:"車",walk:"徒歩",estimate:"所要時間の目安",distance:"移動距離の目安",flow:"移動の流れ",open:"NAVERマップで詳しいルートを見る",notice:"時間と距離は直線距離をもとにした目安です。出発前にNAVERマップで交通状況、バスの到着情報、最終ルートをご確認ください。",transitSteps:["最寄りのバス停または地下鉄駅まで歩く","目的地方面へ移動し、必要に応じて乗り換える","最終停留所からアクティビティエリアまで歩く"],carSteps:["選択した出発地からナビを開始","ナビが案内する速い道路ルートを利用","到着前に周辺の駐車場を確認する"],walkSteps:["歩道と横断歩道に沿って移動","通行可能な海岸遊歩道のみ利用","天候や規制が変わった場合はルートを再確認"]},
  zh:{eyebrow:"交通指南",title:"如何前往",from:"出发地",transit:"公共交通",car:"驾车",walk:"步行",estimate:"预计用时",distance:"预计路程",flow:"建议行程",open:"在NAVER地图查看详细路线",notice:"时间和距离根据直线距离估算。出发前请在NAVER地图确认实时路况、公交到站信息和最终路线。",transitSteps:["步行至附近公交站或地铁站","乘坐前往目的地方向的线路，必要时换乘","从最后一站步行至活动区域"],carSteps:["从所选出发地开启驾车导航","按照导航推荐的快捷道路行驶","抵达前确认活动区域附近停车信息"],walkSteps:["沿人行道和人行横道前进","仅使用允许步行通行的海岸步道","天气或通行限制变化时重新确认路线"]},
} as const;
const origins:{id:OriginId;name:Localized;lat:number;lon:number}[]=[
  {id:"gwangalli",name:L("Gwangalli","광안리","広安里（クァンアンリ）","广安里"),lat:35.1532,lon:129.1187},
  {id:"haeundae",name:L("Haeundae","해운대","海雲台（ヘウンデ）","海云台"),lat:35.1631,lon:129.1635},
  {id:"seomyeon",name:L("Seomyeon","서면","西面（ソミョン）","西面"),lat:35.1578,lon:129.0592},
  {id:"busanStation",name:L("Busan Station","부산역","釜山駅","釜山站"),lat:35.1151,lon:129.0414},
  {id:"nampo",name:L("Nampo-dong","남포동","南浦洞（ナンポドン）","南浦洞"),lat:35.0975,lon:129.0346},
  {id:"gijang",name:L("Gijang","기장","機張（キジャン）","机张"),lat:35.2446,lon:129.2223},
];
type Guide={where:Localized;how:Localized;note:Localized;phone?:string;items:{icon:string;title:Localized;desc:Localized}[]};
const guideUi={
  en:{eyebrow:"WHAT TO DO HERE",title:"Plan your time at",where:"Where to go",how:"How to join",check:"Check before you go",call:"Call to confirm",map:"Open activity area",notice:"Programs, prices and operating hours may change with the season, tides and weather. Confirm directly before traveling."},
  ko:{eyebrow:"이곳에서 뭐 하지?",title:"현장 활동 가이드",where:"어디로 가나요?",how:"어떻게 이용하나요?",check:"가기 전에 확인",call:"운영 문의하기",map:"체험 장소 지도",notice:"프로그램·요금·운영시간은 계절, 물때와 날씨에 따라 달라질 수 있으니 방문 전에 운영처에 확인하세요."},
  ja:{eyebrow:"ここで何ができる？",title:"現地アクティビティガイド",where:"どこへ行く？",how:"参加方法",check:"出発前に確認",call:"営業状況を確認",map:"体験エリアを地図で見る",notice:"プログラム、料金、営業時間は季節・潮位・天候により変わります。訪問前に必ず現地へご確認ください。"},
  zh:{eyebrow:"这里可以怎么玩？",title:"现场活动指南",where:"去哪里体验？",how:"如何参加？",check:"出发前请确认",call:"电话确认运营情况",map:"在地图中查看体验地点",notice:"活动内容、价格及营业时间可能因季节、潮汐和天气而调整，出发前请向运营方确认。"},
} as const;
const A=(icon:string,title:Localized,desc:Localized)=>({icon,title,desc});
const guides:Record<string,Guide>={
  gwangalli:{where:L("Gwangalli SUP Zone and marine leisure centers along the beachfront","광안리해변 SUP Zone과 인근 해양레포츠센터","広安里ビーチのSUP Zoneと周辺マリンレジャーセンター","广安里海滩 SUP Zone及附近水上运动中心"),how:L("Choose a local operator, reserve a lesson or rental, then check in at its beachfront desk.","운영 업체에서 강습 또는 장비 대여를 예약한 뒤 해변 접수처에서 체크인하세요.","運営ショップでレッスンまたはレンタルを予約し、ビーチの受付でチェックインします。","选择当地运营商预订课程或装备租赁，再到海滩服务台签到。"),note:L("Morning sessions are usually calmer. Showers and rest areas are available around the SUP Zone.","대체로 오전 바다가 더 잔잔하며 SUP Zone 주변에 샤워장과 쉼터가 있어요.","比較的穏やかな午前がおすすめ。SUP Zone周辺にはシャワーと休憩スペースがあります。","上午海面通常更平稳，SUP Zone附近设有淋浴和休息区。"),items:[A("🏄",L("Intro SUP lesson","SUP 입문 강습","初心者向けSUPレッスン","桨板入门课"),L("Learn paddling, turning and safe falling with an instructor.","강사와 함께 패들링, 방향 전환, 안전하게 넘어지는 법을 배워요.","パドリング、方向転換、安全な落水方法をインストラクターから学びます。","跟随教练学习划桨、转向和安全落水。")),A("🧘",L("SUP yoga","SUP 요가","SUPヨガ","桨板瑜伽"),L("A balance and wellness session held on a board in calm water.","잔잔한 수면 위 보드에서 균형과 휴식을 즐기는 프로그램이에요.","穏やかな海でボードに乗り、バランスとリラックスを楽しみます。","在平静海面上的桨板进行平衡与放松体验。")),A("🌇",L("Sunset paddle","노을 패들링","サンセットパドル","夕阳划桨"),L("Paddle near shore as the bridge and skyline light up.","해 질 무렵 해안 가까이에서 광안대교 풍경을 즐겨요.","日暮れ時に岸近くを進み、広安大橋の景色を楽しみます。","傍晚沿近岸划行，欣赏广安大桥与城市天际线。"))]},
  songjeong:{where:L("Surf schools and rental shops along Songjeong Beach","송정해수욕장 해변가 서핑숍과 강습 구역","松亭ビーチ沿いのサーフショップとレッスンエリア","松亭海滩沿线的冲浪店和教学区"),how:L("Book a surf school lesson; wetsuit and board rental are normally included or available.","서핑숍에 강습을 예약하세요. 웻슈트와 보드는 포함 또는 별도 대여할 수 있어요.","サーフスクールを予約。ウェットスーツとボードはプランに含まれるか、別途レンタルできます。","提前预订冲浪学校课程，潜水服和冲浪板通常包含或可另行租赁。"),note:L("Beginners should enter only with an instructor and follow the designated surf zone.","초보자는 강사와 함께 지정 서핑 구역을 이용하세요.","初心者は必ずインストラクターと一緒に、指定されたサーフエリアを利用してください。","初学者请跟随教练，并仅在指定冲浪区域活动。"),items:[A("🏄‍♀️",L("Beginner surf lesson","초보 서핑 강습","初心者サーフィンレッスン","初学者冲浪课"),L("Practice on land, then catch small waves with an instructor.","지상 교육 후 강사와 함께 작은 파도부터 타요.","陸上練習の後、インストラクターと小さな波に挑戦します。","先进行岸上练习，再由教练带领尝试小浪。")),A("🏄",L("Board rental","서핑보드 대여","サーフボードレンタル","冲浪板租赁"),L("For experienced surfers who can assess the day’s conditions.","당일 파도 상태를 스스로 판단할 수 있는 경험자에게 적합해요.","当日のコンディションを判断できる経験者向けです。","适合能够自行判断当日海况的有经验者。")),A("☕",L("Beach break","해변 휴식","ビーチでひと休み","海边休息"),L("Rinse off and relax at cafés along the beach after your session.","체험 후 해변 카페에서 쉬며 송정 풍경을 즐겨요.","体験後はビーチ沿いのカフェでひと休み。","体验后可在海滩沿线咖啡馆休息。"))]},
  haeundae:{where:L("The designated swimming area in front of Haeundae Beach","해운대해수욕장 개장 기간 지정 수영 구역","海雲台ビーチの開設期間中の指定遊泳エリア","海云台海水浴场开放期间的指定游泳区"),how:L("Use the lifeguarded zone during the official beach season; rentals are available from beach operators.","공식 개장 기간에는 안전요원이 있는 수영 구역을 이용하고 장비는 현장 운영처에서 대여하세요.","海水浴場の開設期間は監視員のいる遊泳区域を利用し、用品は現地でレンタルします。","正式开放期间请在有救生员的游泳区活动，用品可在现场租赁。"),note:L("Swimming access can be restricted outside the season or during warnings.","비개장 기간이나 기상특보 시에는 입수가 제한될 수 있어요.","開設期間外や気象警報時は遊泳が制限される場合があります。","非开放期或发布天气警报时可能限制下水。"),items:[A("🏊",L("Sea swimming","해수욕","海水浴","海边游泳"),L("Swim inside the buoyed, lifeguarded area.","안전 부표 안쪽의 지정 구역에서 수영해요.","ブイで区切られた監視区域内で泳ぎます。","请在浮标围出的救生员管理区域内游泳。")),A("🏖️",L("Beach recreation","해변 놀이","ビーチレジャー","沙滩活动"),L("Enjoy sand play and seasonal beach facilities.","모래놀이와 계절별 해변 편의시설을 이용해요.","砂遊びや季節限定のビーチ施設を楽しめます。","可体验玩沙及季节性海滩设施。")),A("🚶",L("Dongbaek coastal walk","동백섬 해안 산책","冬柏島の海岸散策","冬柏岛海岸漫步"),L("Continue to the coastal path and Nurimaru views.","동백섬 산책로와 누리마루 전망까지 이어서 즐겨요.","冬柏島の遊歩道からヌリマルの景色へ。","可继续前往冬柏岛步道和Nurimaru观景区。"))]},
  suyeong:{where:L("Yacht boarding desks inside Suyeong Bay Yacht Stadium","수영만요트경기장 내 예약 업체별 승선장","水営湾ヨット競技場内の各社乗船受付","水营湾游艇码头内各运营商登船处"),how:L("Reserve a departure time, arrive early for check-in and carry your passport or booking name.","출항 시간을 예약하고 일찍 도착해 예약자명으로 체크인하세요.","出航時間を予約し、早めに到着して予約名で受付を済ませます。","提前预订出航时间，并提早到达凭预订姓名签到。"),note:L("Routes and departures may change with wind, waves and harbor control.","바람·파도와 항만 통제에 따라 항로와 출항 여부가 바뀔 수 있어요.","風・波・港湾規制により、航路や出航可否が変更される場合があります。","航线及是否出航可能因风浪和港口管制而调整。"),items:[A("☀️",L("Day cruise","주간 요트 투어","デイクルーズ","日间巡航"),L("See Marine City, Haeundae and the coastline from the water.","바다에서 마린시티와 해운대 해안을 감상해요.","海上からマリンシティと海雲台の海岸線を眺めます。","从海上欣赏Marine City与海云台海岸线。")),A("🌇",L("Sunset cruise","선셋 요트 투어","サンセットクルーズ","日落巡航"),L("Sail as the sky changes color around Gwangandaegyo Bridge.","광안대교 주변으로 노을이 물드는 시간에 항해해요.","広安大橋周辺が夕焼けに染まる時間にクルーズします。","在广安大桥周边欣赏晚霞巡航。")),A("🌃",L("Night cruise","야경 요트 투어","ナイトクルーズ","夜景巡航"),L("Enjoy illuminated bridges and the Marine City skyline.","조명이 켜진 광안대교와 마린시티 야경을 즐겨요.","ライトアップされた橋とマリンシティの夜景を楽しみます。","欣赏灯光璀璨的大桥与Marine City夜景。"))]},
  dadaepo:{where:L("Dadaepo Beach and the seasonal marine sports operation area","다대포해수욕장과 계절 운영 해양레포츠 구역","多大浦ビーチと季節営業のマリンスポーツエリア","多大浦海水浴场及季节性水上运动区域"),how:L("Check the seasonal operator or visitor information desk before reserving equipment.","계절별 운영처 또는 관광안내소에 프로그램 운영 여부를 먼저 확인하세요.","季節営業の運営事業者または観光案内所で実施状況を確認してから予約します。","先向季节性运营方或游客中心确认活动是否开放，再预订装备。"),note:L("The wide tidal flat changes significantly with the tide; water activities require an operating program.","조수간만에 따라 수심과 해안선이 크게 달라져 운영 프로그램을 통해 이용해야 해요.","潮の満ち引きで水深と海岸線が大きく変わるため、運営プログラムを利用してください。","潮汐会使水深与岸线明显变化，水上活动须参加正规项目。"),items:[A("🛶",L("Sea kayak","바다 카약","シーカヤック","海上皮划艇"),L("A guided nearshore paddle when a seasonal program is operating.","운영 기간에 가이드와 함께 연안 가까이에서 체험해요.","季節プログラム実施時にガイド付きで岸近くを進みます。","季节性项目开放时，在教练带领下近岸划行。")),A("🏄",L("SUP experience","SUP 체험","SUP体験","桨板体验"),L("Learn basic balance and paddling in a designated area.","지정 구역에서 기본 균형 잡기와 패들링을 배워요.","指定エリアで基本のバランスとパドリングを学びます。","在指定区域学习基础平衡和划桨。")),A("🌅",L("Sunset beach walk","노을 해변 산책","夕日のビーチ散策","日落海滩漫步"),L("Walk the beach and observe the famous western sunset.","넓은 백사장을 걸으며 서쪽 바다의 노을을 감상해요.","広い砂浜を歩き、西の海に沈む夕日を眺めます。","漫步宽阔沙滩，欣赏西侧海面的日落。"))]},
  songdo:{where:L("Songdo Beach marine leisure area and the sheltered beachfront","송도해수욕장 해양레저 구역과 해변 앞 잔잔한 수역","松島ビーチのマリンレジャーエリアと穏やかな沿岸部","松岛海水浴场水上运动区及较平稳的近岸水域"),how:L("Use an authorized seasonal operator for rentals and guided sessions.","계절 운영 해양레저 업체를 통해 장비 대여와 강습을 신청하세요.","季節営業の認可事業者を通してレンタルやレッスンを申し込みます。","请通过季节性正规运营商申请装备租赁和教学。"),note:L("Confirm the operating zone because beach swimming and leisure craft areas may be separated.","해수욕 구역과 레저기구 운항 구역이 나뉠 수 있으니 현장 안내를 확인하세요.","遊泳区域とマリンレジャー区域が分かれる場合があるため、現地案内を確認してください。","游泳区与水上器材活动区可能分开，请遵循现场指引。"),items:[A("🚣",L("Guided kayak","가이드 카약","ガイド付きカヤック","教练带领皮划艇"),L("Paddle the sheltered coast with safety equipment.","안전 장비를 착용하고 잔잔한 연안을 따라 이동해요.","安全装備を着用し、穏やかな沿岸を進みます。","穿戴安全装备，沿平稳近岸水域划行。")),A("🏄",L("SUP rental or lesson","SUP 대여·강습","SUPレンタル・レッスン","桨板租赁或课程"),L("Available when seasonal marine leisure operators are open.","계절 해양레저 운영 기간에 이용할 수 있어요.","季節のマリンレジャー営業期間中に利用できます。","季节性水上运动运营期间可参加。")),A("🚡",L("Coast and skywalk course","해안·스카이워크 코스","海岸・スカイウォークコース","海岸与天空步道路线"),L("Combine the beach with Songdo Skywalk and coastal views.","송도 스카이워크와 해안 풍경을 함께 둘러봐요.","松島スカイウォークと海岸の景色を合わせて楽しみます。","可串联松岛天空步道与海岸景观游览。"))]},
  ilgwang:{where:L("The designated swimming section and quiet shoreline at Ilgwang Beach","일광해수욕장 지정 수영 구역과 완만한 해변","日光ビーチの指定遊泳エリアと穏やかな海岸","日光海水浴场指定游泳区及平缓海岸"),how:L("Swim only during the official season and use any water program through its on-site operator.","공식 개장 기간 지정 구역에서 수영하고 수상 체험은 현장 운영처를 이용하세요.","公式開設期間の指定エリアで泳ぎ、水上体験は現地の運営事業者を利用します。","仅在正式开放期的指定区域游泳，水上项目请通过现场运营方参加。"),note:L("Facilities and lifeguards are seasonal; check opening dates before visiting.","편의시설과 안전요원은 계절 운영이므로 개장 기간을 확인하세요.","施設と監視員は季節営業のため、開設期間をご確認ください。","设施及救生员为季节性配置，请提前确认开放日期。"),items:[A("🤿",L("Relaxed swimming","한적한 해수욕","のんびり海水浴","悠闲海泳"),L("Enjoy a quieter beach atmosphere inside the safe zone.","안전 구역 안에서 비교적 한적한 분위기의 해수욕을 즐겨요.","安全区域内で比較的落ち着いた海水浴を楽しめます。","可在安全区域内享受相对安静的海泳体验。")),A("🏖️",L("Family beach play","가족 모래놀이","家族で砂遊び","亲子沙滩活动"),L("The gentle sandy shore suits children with close supervision.","완만한 모래 해변에서 보호자와 함께 놀이를 즐겨요.","なだらかな砂浜で、保護者と一緒に遊べます。","平缓沙滩适合儿童在家长看护下玩耍。")),A("🚶",L("Village coast walk","마을 해안 산책","海辺のまち歩き","渔村海岸漫步"),L("Walk the compact beach and nearby coastal village.","아담한 해변과 주변 해안마을을 천천히 걸어요.","コンパクトなビーチと周辺の海辺の町を歩きます。","沿小巧海滩与周边海岸村落悠闲散步。"))]},
  oryukdo:{where:L("Oryukdo Skywalk and the Haeparang coastal trail entrance","오륙도 스카이워크와 해파랑길 시작 구간","五六島スカイウォークと海波朗道の入口","五六岛天空步道及海波浪路起点"),how:L("This is a land-based coastal experience. Follow the signed trail and viewing areas.","물에 들어가는 활동이 아닌 해안 경관 체험으로, 안내된 산책로와 전망 구역을 이용하세요.","海に入る体験ではありません。案内表示に沿って遊歩道と展望エリアを利用します。","这里以陆上观海体验为主，请沿标识步道和观景区域游览。"),note:L("The skywalk may close in strong wind or poor weather; cliff edges require care.","강풍·악천후에는 스카이워크가 통제될 수 있으며 절벽 구간에서는 주의하세요.","強風や悪天候時はスカイウォークが閉鎖される場合があります。崖沿いでは十分ご注意ください。","强风或恶劣天气时天空步道可能关闭，悬崖路段请注意安全。"),items:[A("🌉",L("Skywalk viewing","스카이워크 전망","スカイウォーク展望","天空步道观景"),L("Look down at the rocky coast and Oryukdo islets.","유리 전망대에서 암석 해안과 오륙도를 내려다봐요.","ガラス展望台から岩場の海岸と五六島を眺めます。","从玻璃观景台俯瞰岩岸与五六岛。")),A("🥾",L("Coastal trail","해파랑길 걷기","海岸トレイル","海岸徒步"),L("Walk a section of the Haeparang trail with open sea views.","탁 트인 바다를 보며 해파랑길 일부 구간을 걸어요.","海を眺めながら海波朗道の一部を歩きます。","沿海波浪路部分路段徒步，欣赏开阔海景。")),A("📷",L("Cliff photography","절벽 해안 촬영","断崖の写真撮影","悬崖海岸拍摄"),L("Use the marked viewpoints for dramatic coastal photos.","지정 전망대에서 역동적인 해안 풍경을 촬영해요.","指定の展望スポットから迫力ある海岸を撮影します。","在指定观景点拍摄壮观海岸风景。"))]},
  taejongdae:{where:L("Taejongdae park trails, observatory and coastal viewpoints","태종대유원지 산책로와 전망대·해안 전망 구간","太宗台公園の遊歩道・展望台・海岸ビューポイント","太宗台公园步道、观景台及海岸观景区"),how:L("Follow park trails or use the seasonal park train; boat services should be checked separately.","공원 산책로를 걷거나 순환열차를 이용하고, 유람선은 별도 운항 여부를 확인하세요.","園内を歩くか循環列車を利用し、遊覧船は別途運航状況を確認してください。","可步行游览或乘坐园区循环车，游船须另行确认是否运营。"),note:L("Rocky shore access can be restricted by waves, wind or maintenance.","파도·바람 또는 시설 점검에 따라 암석 해안 접근이 제한될 수 있어요.","波・風・点検により、岩場の海岸への立ち入りが制限される場合があります。","受风浪或设施维护影响，岩岸区域可能限制进入。"),items:[A("🥾",L("Cliffside trail","절벽 해안 산책","断崖沿いの散策","悬崖海岸徒步"),L("Walk through forest to wide-open sea viewpoints.","숲길을 지나 탁 트인 바다 전망대까지 걸어요.","森の道を抜け、海を一望できる展望台へ歩きます。","穿过林间步道前往开阔海景观景台。")),A("🔭",L("Observatory views","전망대 관람","展望台","观景台眺望"),L("See the offshore islands and passing ships on clear days.","맑은 날에는 먼 섬과 오가는 선박을 볼 수 있어요.","晴れた日には沖の島々や行き交う船を眺められます。","天气晴朗时可远眺岛屿和往来船只。")),A("⛴️",L("Coastal sightseeing boat","해안 유람선","海岸遊覧船","海岸观光船"),L("If operating, confirm departure point and sea conditions on the day.","운항 중이라면 당일 승선장과 해상 상태를 확인하세요.","運航している場合は、当日の乗り場と海況をご確認ください。","如当日运营，请确认登船点及海况。"))]},
  gijang:{where:L("Gongsu Fishing Village Experience Center, 18 Gongsu 1-gil, Gijang","기장군 기장읍 공수1길 18 공수어촌체험휴양마을","機張郡機張邑公須1キル18・公須漁村体験休養村","机张郡机张邑公须1街18号，公须渔村体验休养村"),how:L("Programs are reservation-based. Call the village to match your visit with the tide and available instructor.","체험은 예약제로 운영될 수 있어 마을에 전화해 물때와 강사 운영 시간을 맞추세요.","体験は予約制の場合があります。村へ電話し、潮位と担当者の実施時間をご確認ください。","体验项目可能采用预约制，请致电村庄，根据潮汐及讲师时间安排行程。"),note:L("Intertidal and fishing programs depend strongly on tides. Ask which programs run on your date.","조간대·어업 체험은 물때의 영향을 크게 받으므로 방문일에 가능한 프로그램을 꼭 문의하세요.","磯や漁業体験は潮位の影響を大きく受けます。訪問日に実施できる内容を必ずお問い合わせください。","潮间带和渔业体验受潮汐影响较大，请务必确认到访当天可参加的项目。"),phone:"051-723-1919",items:[A("🐟",L("Traditional haul-net fishing","전통 후릿그물 체험","伝統の地引き網体験","传统拉网捕鱼体验"),L("Work as a group to pull a traditional shore net and learn how villagers fish.","여럿이 함께 전통 그물을 당기며 어촌의 고기잡이 방식을 배워요.","みんなで伝統の網を引き、漁村の漁法を体験します。","多人协作拉起传统渔网，了解渔村捕鱼方式。")),A("🦀",L("Intertidal ecology","조간대 생태학습","磯の生態観察","潮间带生态观察"),L("Explore the rocky shore at low tide and learn about small marine life.","간조 때 바위 해안을 살피며 작은 해양생물을 관찰해요.","干潮時の岩場で小さな海の生き物を観察します。","退潮时探索岩岸，观察小型海洋生物。")),A("♻️",L("Beachcombing craft","비치코밍·만들기","ビーチコーミング・ものづくり","海滩清理与手作"),L("Collect safe shoreline materials and turn sea glass into a keepsake.","안전하게 해안 표류물을 모으고 씨글라스로 기념품을 만들어요.","安全に漂着物を集め、シーグラスで思い出の品を作ります。","安全收集海岸漂流物，并用海玻璃制作纪念品。"))]},
  amnam:{where:L("Amnam Park Breakwater, 620-4 Amnam-dong, Seo-gu","부산 서구 암남동 620-4 암남공원 방파제","釜山広域市西区岩南洞620-4・岩南公園防波堤","釜山市西区岩南洞620-4，岩南公园防波堤"),how:L("Bring or rent fishing gear before arrival, set up only in an open breakwater area and keep clear of other lines.","낚싯대와 채비를 미리 준비한 뒤 출입이 허용된 방파제 구역에서 다른 낚싯줄과 간격을 두고 이용하세요.","釣具を用意し、立入可能な防波堤エリアで周囲の釣り糸と間隔を取って楽しみます。","请提前准备钓具，仅在开放的防波堤区域垂钓，并与其他钓线保持距离。"),note:L("Wear a life jacket and non-slip shoes. The breakwater is closed during typhoons or severe weather.","구명조끼와 미끄럼 방지 신발을 착용하세요. 태풍 등 기상 악화 시에는 출입이 통제됩니다.","ライフジャケットと滑りにくい靴を着用。台風などの悪天候時は立入禁止です。","请穿救生衣和防滑鞋；台风等恶劣天气时将限制进入。"),items:[A("🎣",L("Breakwater fishing","방파제 생활낚시","堤防釣り","防波堤垂钓"),L("Fish from the open breakwater while checking waves and nearby anglers.","파도와 주변 낚시인을 살피며 개방된 방파제에서 생활낚시를 즐겨요.","波と周囲を確認しながら、開放された防波堤で釣りを楽しみます。","观察浪况和周边钓友，在开放防波堤区域垂钓。")),A("🐟",L("Seasonal catch","계절 어종 확인","季節の魚","当季鱼种"),L("Possible catch changes by season and tide; local tackle shops can advise on the day.","잡히는 어종은 계절과 물때에 따라 달라지므로 당일 현지 낚시점에 채비를 문의하세요.","釣れる魚は季節と潮で変わるため、当日に地元の釣具店で確認してください。","鱼种随季节和潮汐变化，建议当天向当地渔具店咨询。")),A("🥾",L("Coastal walk","암남공원 해안 산책","海岸散策","海岸漫步"),L("Combine fishing with Amnam Park’s coastal trail and sea views.","낚시 전후로 암남공원 산책로와 해안 절경을 함께 즐겨요.","釣りの前後に岩南公園の海岸遊歩道も楽しめます。","垂钓前后可游览岩南公园海岸步道。"))]},
};
const base:Spot[]=[
  {id:"gwangalli",name:L("Gwangalli Beach","광안리해수욕장","広安里（クァンアンリ）海水浴場","广安里海水浴场"),activity:L("Sunset SUP","노을 SUP","夕暮れのSUP","夕阳桨板"),kind:"sup",categories:["activity","relax"],icon:"🏄",lat:35.1532,lon:129.1187,distance:1.2,water:23.8,wave:.35,wind:2.4,temp:26,rain:0,crowd:38,group:[1,6]},
  {id:"songjeong",name:L("Songjeong Beach","송정해수욕장","松亭（ソンジョン）海水浴場","松亭海水浴场"),activity:L("Beginner surfing","초보 서핑","初心者向けサーフィン","初学者冲浪"),kind:"surf",categories:["activity"],icon:"🏄‍♀️",lat:35.1786,lon:129.1997,distance:7.6,water:24.1,wave:.85,wind:3.8,temp:27,rain:0,crowd:44,group:[1,4]},
  {id:"haeundae",name:L("Haeundae Beach","해운대해수욕장","海雲台（ヘウンデ）海水浴場","海云台海水浴场"),activity:L("Sea swimming","해수욕","海水浴","海边游泳"),kind:"swim",categories:["activity","relax","kids"],icon:"🏊",lat:35.1587,lon:129.1604,distance:4.9,water:24,wave:.48,wind:3.2,temp:27,rain:0,crowd:78,group:[1,8]},
  {id:"suyeong",name:L("Suyeong Bay","수영만요트경기장","水営湾ヨット競技場","水营湾游艇码头"),activity:L("Yacht cruise","요트 투어","ヨットクルーズ","游艇观光"),kind:"yacht",categories:["activity","relax","kids"],icon:"⛵",lat:35.1589,lon:129.1354,distance:2.8,water:23.7,wave:.42,wind:4.1,temp:26,rain:0,crowd:52,group:[4,10]},
  {id:"dadaepo",name:L("Dadaepo Beach","다대포해수욕장","多大浦（タデポ）海水浴場","多大浦海水浴场"),activity:L("Sunset kayaking","노을 카약","夕暮れのカヤック","夕阳皮划艇"),kind:"kayak",categories:["activity","relax","kids"],icon:"🛶",lat:35.0467,lon:128.9655,distance:15.8,water:24.4,wave:.28,wind:2.9,temp:27,rain:0,crowd:29,group:[2,6]},
  {id:"songdo",name:L("Songdo Beach","송도해수욕장","松島（ソンド）海水浴場","松岛海水浴场"),activity:L("Coastal kayak","해안 카약","シーカヤック","海岸皮划艇"),kind:"kayak",categories:["activity","kids"],icon:"🚣",lat:35.0759,lon:129.0168,distance:10.6,water:23.9,wave:.32,wind:3,temp:26,rain:0,crowd:35,group:[2,8]},
  {id:"ilgwang",name:L("Ilgwang Beach","일광해수욕장","日光（イルグァン）海水浴場","日光海水浴场"),activity:L("Quiet swimming","한적한 해수욕","のんびり海水浴","悠闲海泳"),kind:"swim",categories:["relax","kids"],icon:"🤿",lat:35.2593,lon:129.2331,distance:19.4,water:23.6,wave:.4,wind:3.5,temp:26,rain:0,crowd:21,group:[1,8]},
  {id:"oryukdo",name:L("Oryukdo Skywalk","오륙도 해맞이공원","五六島（オリュクト）スカイウォーク","五六岛天空步道"),activity:L("Coastal walk","해안 산책","海辺の散策","海岸漫步"),kind:"walk",categories:["relax","kids"],icon:"🥾",lat:35.1008,lon:129.1238,distance:8.7,water:23.4,wave:.72,wind:4.6,temp:25,rain:0,crowd:33,group:[1,10]},
  {id:"taejongdae",name:L("Taejongdae Coast","태종대 해안","太宗台（テジョンデ）海岸","太宗台海岸"),activity:L("Cliffside walk","절벽 해안 산책","海岸トレッキング","海岸徒步"),kind:"walk",categories:["relax","kids"],icon:"🌊",lat:35.0526,lon:129.0872,distance:14.2,water:23.2,wave:.9,wind:5.2,temp:25,rain:0,crowd:27,group:[1,10]},
  {id:"gijang",name:L("Gongsu Fishing Village","기장 공수어촌체험마을","機張（キジャン）公須漁村","机张公须渔村"),activity:L("Village sea experience","어촌 해양체험","漁村体験","渔村体验"),kind:"walk",categories:["kids"],icon:"🎣",lat:35.1849,lon:129.2079,distance:10.3,water:23.5,wave:.58,wind:3.9,temp:26,rain:0,crowd:18,group:[2,10]},
  {id:"amnam",name:L("Amnam Park Breakwater","암남공원 방파제","岩南公園防波堤","岩南公园防波堤"),activity:L("Breakwater fishing","방파제 낚시","堤防釣り","防波堤垂钓"),kind:"fishing",categories:["fishing","relax"],icon:"🎣",lat:35.0617,lon:129.018,distance:12.1,water:23.8,wave:.45,wind:3.2,temp:26,rain:0,crowd:31,group:[1,4]},
];

function seaScore(s:Spot){
  if(s.kind==="surf") return Math.max(0,100-Math.abs(s.wave-1.05)*70-Math.max(0,s.wind-6)*10);
  if(s.kind==="sup"||s.kind==="kayak") return Math.max(0,100-s.wave*70-Math.max(0,s.wind-4)*13);
  if(s.kind==="swim") return Math.max(0,100-Math.abs(s.water-25)*7-s.wave*45-Math.max(0,s.wind-5)*12);
  if(s.kind==="yacht") return Math.max(0,100-Math.abs(s.wind-4)*7-s.wave*32);
  if(s.kind==="fishing") return Math.max(0,100-s.wave*30-Math.max(0,s.wind-6)*12);
  return Math.max(0,100-Math.max(0,s.wave-1)*25-Math.max(0,s.wind-7)*10);
}
function distanceKm(a:{lat:number;lon:number},b:{lat:number;lon:number}){
  const rad=(n:number)=>n*Math.PI/180; const dLat=rad(b.lat-a.lat); const dLon=rad(b.lon-a.lon);
  const h=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;
  return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));
}
function score(s:Spot,people:number){
  const weather=Math.max(0,100-Math.abs(s.temp-25)*4-s.rain*7-Math.max(0,s.wind-8)*6);
  const sea=seaScore(s); const crowd=100-s.crowd; const distance=Math.max(20,100-s.distance*4.3);
  const group=people>=s.group[0]&&people<=s.group[1]?100:Math.max(20,100*Math.min(people,s.group[1])/Math.max(people,s.group[0]));
  let total=Math.round(weather*.24+sea*.36+crowd*.16+distance*.14+group*.1);
  const unsafe=(s.kind==="swim"&&s.wave>1.2)||(s.kind==="sup"&&s.wave>.9)||(s.kind==="kayak"&&s.wave>1.1)||(s.kind==="fishing"&&(s.wave>1.2||s.wind>8))||s.wind>10||s.rain>8;
  if(unsafe) total=Math.min(total,54);
  return {total,weather:Math.round(weather),sea:Math.round(sea),crowd:Math.round(crowd),distance:Math.round(distance),group:Math.round(group),unsafe};
}

type Reason={icon:string;title:string;text:string};
function recommendationReasons(s:Spot,people:number,lang:Lang):Reason[]{
  const pick=(value:Localized)=>value[lang];
  const calm=s.wave<=.7; const lowCrowd=s.crowd<=35; const groupFits=people>=s.group[0]&&people<=s.group[1];
  const seaTitles:Record<Spot["kind"],Localized>={
    surf:L("Surfable waves","서핑에 맞는 파도","サーフィン向きの波","适合冲浪的浪况"),
    sup:L("Calmer water for SUP","SUP에 유리한 잔잔한 파도","SUP向きの穏やかな海","适合桨板的平稳水面"),
    kayak:L("Manageable kayak conditions","카약에 유리한 파도","カヤック向きの海況","适合皮划艇的浪况"),
    swim:L("Swimming conditions","수영하기 좋은 수온과 파도","泳ぎやすい水温と波","适合游泳的水温与浪况"),
    yacht:L("Stable cruise conditions","요트 운항에 유리한 바다","クルーズ向きの海況","适合游艇航行的海况"),
    walk:L("Comfortable coastal weather","해안 활동에 좋은 날씨","海辺を歩きやすい天気","适合海岸活动的天气"),
    fishing:L("Breakwater fishing conditions","방파제 낚시를 판단하는 바다 조건","堤防釣りの海況","防波堤垂钓海况"),
  };
  const seaTexts:Record<Spot["kind"],Localized>={
    surf:L(`Waves are ${s.wave.toFixed(1)} m with ${s.wind.toFixed(1)} m/s wind—usable surf conditions, subject to instructor checks.`,`파도 ${s.wave.toFixed(1)}m, 바람 ${s.wind.toFixed(1)}m/s로 서핑 가능한 조건이며 초보자는 강사 확인이 필요해요.`,`波は${s.wave.toFixed(1)}m、風は${s.wind.toFixed(1)}m/s。インストラクターの確認のもとで楽しめるコンディションです。`,`浪高${s.wave.toFixed(1)}米、风速${s.wind.toFixed(1)}米/秒，具备冲浪条件，初学者须听从教练判断。`),
    sup:L(`Waves are ${s.wave.toFixed(1)} m and wind is ${s.wind.toFixed(1)} m/s${calm?", keeping the surface relatively calm":"; confirm the operator is running before entering"}.`,`파도 ${s.wave.toFixed(1)}m, 바람 ${s.wind.toFixed(1)}m/s${calm?"로 수면이 비교적 잔잔해요":"이므로 입수 전 운영 여부를 확인해야 해요"}.`,`波は${s.wave.toFixed(1)}m、風は${s.wind.toFixed(1)}m/s。${calm?"比較的穏やかです。":"実施状況を確認してください。"}`,`浪高${s.wave.toFixed(1)}米、风速${s.wind.toFixed(1)}米/秒，${calm?"水面相对平稳。":"下水前请确认项目是否运营。"}`),
    kayak:L(`Waves are ${s.wave.toFixed(1)} m with ${s.wind.toFixed(1)} m/s wind${calm?", suitable for a guided nearshore paddle":"; an operator check is needed"}.`,`파도 ${s.wave.toFixed(1)}m, 바람 ${s.wind.toFixed(1)}m/s${calm?"로 가이드 동반 연안 체험에 유리해요":"이므로 운영처의 안전 확인이 필요해요"}.`,`波は${s.wave.toFixed(1)}m、風は${s.wind.toFixed(1)}m/s。${calm?"ガイド付きの沿岸体験に向いています。":"運営者の安全確認が必要です。"}`,`浪高${s.wave.toFixed(1)}米、风速${s.wind.toFixed(1)}米/秒，${calm?"适合由教练带领的近岸体验。":"须由运营方确认安全状况。"}`),
    swim:L(`Water is ${s.water.toFixed(1)}°C with ${s.wave.toFixed(1)} m waves${calm?", giving relatively comfortable swimming conditions":"; use only an open, lifeguarded zone"}.`,`수온 ${s.water.toFixed(1)}°C, 파도 ${s.wave.toFixed(1)}m${calm?"로 비교적 편안하게 수영할 수 있는 조건이에요":"이므로 개장한 안전 구역만 이용해야 해요"}.`,`水温${s.water.toFixed(1)}°C、波${s.wave.toFixed(1)}m。${calm?"比較的泳ぎやすい状態です。":"監視員のいる遊泳区域だけを利用してください。"}`,`水温${s.water.toFixed(1)}°C、浪高${s.wave.toFixed(1)}米，${calm?"游泳条件相对舒适。":"请仅在开放且有救生员的区域游泳。"}`),
    yacht:L(`Waves are ${s.wave.toFixed(1)} m with ${s.wind.toFixed(1)} m/s wind${calm?", favorable for a smoother cruise":"; departure needs operator confirmation"}.`,`파도 ${s.wave.toFixed(1)}m, 바람 ${s.wind.toFixed(1)}m/s${calm?"로 비교적 편안한 운항에 유리해요":"이므로 출항 여부를 확인해야 해요"}.`,`波は${s.wave.toFixed(1)}m、風は${s.wind.toFixed(1)}m/s。${calm?"比較的穏やかなクルーズが期待できます。":"出航状況の確認が必要です。"}`,`浪高${s.wave.toFixed(1)}米、风速${s.wind.toFixed(1)}米/秒，${calm?"有利于较平稳的巡航。":"请先确认是否出航。"}`),
    walk:L(`It is ${s.temp.toFixed(1)}°C with ${s.rain.toFixed(1)} mm precipitation and ${s.wind.toFixed(1)} m/s wind.`,`기온 ${s.temp.toFixed(1)}°C, 강수 ${s.rain.toFixed(1)}mm, 바람 ${s.wind.toFixed(1)}m/s로 해안 활동 조건을 판단했어요.`,`気温${s.temp.toFixed(1)}°C、降水${s.rain.toFixed(1)}mm、風${s.wind.toFixed(1)}m/sです。`,`气温${s.temp.toFixed(1)}°C、降水${s.rain.toFixed(1)}毫米、风速${s.wind.toFixed(1)}米/秒。`),
    fishing:L(`Waves are ${s.wave.toFixed(1)} m with ${s.wind.toFixed(1)} m/s wind. Breakwater access may close in severe weather.`,`현재 파도 ${s.wave.toFixed(1)}m, 바람 ${s.wind.toFixed(1)}m/s예요. 기상 악화 시 방파제 출입이 통제될 수 있어요.`,`波は${s.wave.toFixed(1)}m、風は${s.wind.toFixed(1)}m/s。悪天候時は堤防が閉鎖される場合があります。`,`当前浪高${s.wave.toFixed(1)}米、风速${s.wind.toFixed(1)}米/秒。天气恶劣时防波堤可能关闭。`),
  };
  const crowdTitle=L(lowCrowd?"More room to enjoy":"Crowd level considered",lowCrowd?"비교적 여유로운 혼잡도":"혼잡도를 함께 반영",lowCrowd?"比較的ゆったり":"混雑度も考慮",lowCrowd?"相对从容":"已考虑拥挤程度");
  const crowdText=L(`Estimated crowding is ${s.crowd}%${lowCrowd?", leaving more space for your activity":"; quieter times may be more comfortable"}.`,`예상 혼잡도 ${s.crowd}%${lowCrowd?"로 활동할 공간이 비교적 여유로워요":"이며 한산한 시간대를 이용하면 더 편안해요"}.`,`予想混雑度は${s.crowd}%${lowCrowd?"で、比較的ゆったり楽しめます。":"。空いている時間帯がおすすめです。"}`,`预计拥挤度为${s.crowd}%，${lowCrowd?"活动空间相对充足。":"选择较空闲时段会更舒适。"}`);
  const accessTitle=L("Practical for your group","현재 위치와 인원에 적합","現在地と人数に合う","符合当前位置与人数");
  const accessText=L(`It is ${s.distance.toFixed(1)} km straight-line from your start, and ${people} ${people===1?"person is":"people are"} ${groupFits?"within the recommended group size":"outside the usual group range"}.`,`출발지에서 직선거리 ${s.distance.toFixed(1)}km이고, ${people}명은 ${groupFits?"권장 인원 범위에 들어요":"일반 권장 인원 범위를 벗어나 운영처 확인이 필요해요"}.`,`出発地から直線${s.distance.toFixed(1)}km。${people}人は${groupFits?"推奨人数の範囲内です。":"通常の推奨人数外のため確認が必要です。"}`,`距出发地直线${s.distance.toFixed(1)}公里，${people}人${groupFits?"符合建议人数范围。":"超出常规建议人数，需向运营方确认。"}`);
  return [{icon:s.kind==="walk"?"☀️":"🌊",title:pick(seaTitles[s.kind]),text:pick(seaTexts[s.kind])},{icon:"👥",title:pick(crowdTitle),text:pick(crowdText)},{icon:"📍",title:pick(accessTitle),text:pick(accessText)}];
}

type ThemePanel={eyebrow:string;title:string;intro:string;cards:Reason[]};
function categoryPanel(category:Category,s:Spot,guide:Guide,lang:Lang):ThemePanel{
  const pick=(value:Localized)=>value[lang];
  const spotName=s.name[lang];
  if(category==="activity") return {
    eyebrow:pick(L("ACTIVE DAY","액티비티를 골랐어요","アクティブに楽しむ","动感体验")),
    title:pick(L(`What you can do at ${spotName}`,`${spotName}에서 할 수 있는 활동`,`「${spotName}」でできること`,`${spotName}可体验的活动`)),
    intro:pick(L("We matched an active program first. Choose a lesson or guided option that is operating today.","몸을 움직이는 해양활동이 가능한 장소를 먼저 골랐어요. 오늘 운영하는 강습이나 가이드 프로그램을 선택하세요.","体を動かすプログラムを優先しました。当日実施中のレッスンやガイドツアーを選びましょう。","优先推荐可参与运动项目的地点，请选择当天开放的课程或教练带领项目。")),
    cards:guide.items.map(item=>({icon:item.icon,title:item.title[lang],text:item.desc[lang]})),
  };
  if(category==="fishing") return {
    eyebrow:pick(L("FISHING PLAN","낚시 장소를 찾았어요","釣りプラン","垂钓计划")),
    title:pick(L(`Where and how to fish at ${spotName}`,`${spotName}에서 어디서 어떻게 낚시할까요?`,`「${spotName}」でどこからどう釣る？`,`${spotName}在哪里、怎样垂钓？`)),
    intro:pick(L("This recommendation is for shore fishing from an open breakwater—not a boat tour or fishing village program.","배낚시나 어촌 체험이 아니라, 출입이 허용된 방파제에서 즐기는 생활낚시 기준 추천이에요.","船釣りや漁村体験ではなく、立入可能な防波堤からの釣りを想定しています。","这是开放防波堤岸钓推荐，并非船钓或渔村体验。")),
    cards:[{icon:"📍",title:pick(L("Fishing point","낚시 포인트","釣りポイント","垂钓位置")),text:guide.where[lang]},{icon:"🎣",title:guide.items[0].title[lang],text:guide.how[lang]},{icon:"🦺",title:pick(L("Gear and safety","준비물과 안전","装備と安全","装备与安全")),text:guide.note[lang]}],
  };
  if(category==="kids") return {
    eyebrow:pick(L("FAMILY DAY","아이와 함께 가요","子どもと一緒","亲子出游")),
    title:pick(L(`Why ${spotName} works for families`,`${spotName}가 아이와 가기 좋은 점`,`「${spotName}」が家族に向く理由`,`${spotName}适合亲子出游的理由`)),
    intro:pick(L("We prioritized places where children can join an experience, learn something new and stay close to a guardian.","아이가 직접 참여하고 새로운 것을 배우며 보호자와 함께 움직이기 좋은 장소를 우선했어요.","子どもが体験に参加し、学びながら保護者と一緒に過ごしやすい場所を優先しました。","优先选择儿童能够参与、学习，并便于家长陪同的地点。")),
    cards:[{icon:"🧒",title:pick(L("Hands-on experience","아이가 직접 체험해요","子どもが体験できる","儿童亲手体验")),text:`${guide.items[0].title[lang]} — ${guide.items[0].desc[lang]}`},{icon:"💡",title:pick(L("More than one option","아이 성향에 맞게 골라요","興味に合わせて選べる","可按孩子兴趣选择")),text:`${guide.items[1].title[lang]} — ${guide.items[1].desc[lang]}`},{icon:"🤝",title:pick(L("Plan it with a guardian","보호자와 안전하게","保護者と安全に","家长陪同更安心")),text:guide.note[lang]}],
  };
  if(category==="relax") return {
    eyebrow:pick(L("SLOW COAST","편안하게 쉬어요","海辺でのんびり","轻松看海")),
    title:pick(L(`A slower plan at ${spotName}`,`${spotName}에서 편안하게 보내는 방법`,`「${spotName}」でのんびり過ごす`,`在${spotName}轻松度过一天`)),
    intro:pick(L("We favored manageable sea conditions, a lower crowd estimate and activities you can enjoy at your own pace.","부담이 적은 바다 상태와 비교적 낮은 혼잡도, 천천히 즐길 수 있는 활동을 우선했어요.","穏やかな海況、比較的低い混雑度、自分のペースで楽しめる過ごし方を優先しました。","优先考虑较平稳的海况、较低的预计拥挤度和可慢慢体验的活动。")),
    cards:[{icon:"🌊",title:pick(L("Sea right now","지금 바다 상태","現在の海況","当前海况")),text:pick(L(`Waves ${s.wave.toFixed(1)} m · wind ${s.wind.toFixed(1)} m/s`,`파도 ${s.wave.toFixed(1)}m · 바람 ${s.wind.toFixed(1)}m/s`,`波${s.wave.toFixed(1)}m・風${s.wind.toFixed(1)}m/s`,`浪高${s.wave.toFixed(1)}米 · 风速${s.wind.toFixed(1)}米/秒`))},{icon:"👥",title:pick(L("Expected crowd","예상 혼잡도","予想混雑度","预计拥挤度")),text:pick(L(`${s.crowd}% estimated today`,`오늘 ${s.crowd}% 예상`,`本日は${s.crowd}%予想`,`今日预计${s.crowd}%`))},{icon:guide.items[0].icon,title:guide.items[0].title[lang],text:guide.items[0].desc[lang]}],
  };
  return {
    eyebrow:pick(L("TODAY'S OVERALL MATCH","오늘의 전체 추천","今日の総合おすすめ","今日综合推荐")),
    title:pick(L(`Why start with ${spotName}?`,`오늘은 ${spotName}부터 살펴보세요`,`今日は「${spotName}」から`,`今天先看看${spotName}`)),
    intro:pick(L("This is the highest overall match before choosing a travel style. Pick a button above to see a purpose-specific plan.","여행 방식을 고르기 전 전체 조건의 1순위예요. 위 버튼을 누르면 목적에 맞는 장소와 설명으로 바로 바뀝니다.","過ごし方を選ぶ前の総合1位です。上のボタンを押すと目的別の場所と案内に切り替わります。","这是尚未选择出游方式时的综合第一名。点击上方按钮即可切换为对应主题的地点和说明。")),
    cards:[{icon:s.icon,title:s.activity[lang],text:guide.items[0].desc[lang]},{icon:"🌊",title:pick(L("Sea conditions","바다 조건","海況","海况")),text:pick(L(`Waves ${s.wave.toFixed(1)} m · water ${s.water.toFixed(1)}°C`,`파도 ${s.wave.toFixed(1)}m · 수온 ${s.water.toFixed(1)}°C`,`波${s.wave.toFixed(1)}m・水温${s.water.toFixed(1)}°C`,`浪高${s.wave.toFixed(1)}米 · 水温${s.water.toFixed(1)}°C`))},{icon:"📍",title:pick(L("From your start","출발지에서","出発地から","距出发地")),text:`${s.distance.toFixed(1)} km`}],
  };
}

async function liveSpot(s:Spot):Promise<Spot>{
  const weatherUrl=`https://api.open-meteo.com/v1/forecast?latitude=${s.lat}&longitude=${s.lon}&current=temperature_2m,precipitation,wind_speed_10m&wind_speed_unit=ms&timezone=Asia%2FSeoul`;
  const marineUrl=`https://marine-api.open-meteo.com/v1/marine?latitude=${s.lat}&longitude=${s.lon}&hourly=wave_height,sea_surface_temperature&forecast_days=1&timezone=Asia%2FSeoul`;
  const [w,m]=await Promise.all([fetch(weatherUrl),fetch(marineUrl)]); if(!w.ok||!m.ok) throw new Error("feed");
  const wd=await w.json(); const md=await m.json(); const now=new Date(); const hour=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}T${String(now.getHours()).padStart(2,"0")}:00`;
  const i=Math.max(0,md.hourly.time.indexOf(hour));
  return {...s,temp:wd.current.temperature_2m,rain:wd.current.precipitation,wind:wd.current.wind_speed_10m,wave:md.hourly.wave_height[i]??s.wave,water:md.hourly.sea_surface_temperature[i]??s.water};
}

const LEGACY_PREFERENCES_KEY="ocean-log:busan-blue-preferences:v1";
const defaultLegacyPreferences={people:2,category:"all" as Category,originId:"gwangalli" as OriginId,origin:{lat:origins[0].lat,lon:origins[0].lon}};
function readLegacyPreferences(){
  if(typeof window==="undefined")return defaultLegacyPreferences;
  try{
    const parsed=JSON.parse(window.localStorage.getItem(LEGACY_PREFERENCES_KEY)??"");
    const validOrigin=origins.some(item=>item.id===parsed.originId);
    const validCategory=["all","activity","fishing","relax","kids"].includes(parsed.category);
    return {people:Math.min(10,Math.max(1,Number(parsed.people)||2)),category:(validCategory?parsed.category:"all") as Category,originId:(validOrigin?parsed.originId:"gwangalli") as OriginId,origin:{lat:Number(parsed.origin?.lat)||origins[0].lat,lon:Number(parsed.origin?.lon)||origins[0].lon}};
  }catch{return defaultLegacyPreferences}
}

export function LegacyRecommendationPage({initialLanguage="en",onLanguageChange,view="recommend"}:{initialLanguage?:Lang;onLanguageChange?:(language:Lang)=>void;view?:LegacyView}){
  const router=useRouter(); const [initialPreferences]=useState(readLegacyPreferences); const [lang,setLang]=useState<Lang>(initialLanguage); const [people,setPeople]=useState(initialPreferences.people); const [category,setCategory]=useState<Category>(initialPreferences.category); const [spots,setSpots]=useState(base); const [loading,setLoading]=useState(false); const [live,setLive]=useState(false); const [updated,setUpdated]=useState(""); const [originId,setOriginId]=useState<OriginId>(initialPreferences.originId); const [origin,setOrigin]=useState(initialPreferences.origin); const [geoState,setGeoState]=useState<"idle"|"loading"|"success"|"error">("idle"); const [travelMode,setTravelMode]=useState<TravelMode>("transit"); const [unitPreferences,setUnitPreferences]=useState(DEFAULT_UNIT_PREFERENCES); const t=ui[lang]; const lt=locationUi[lang];
  const selectLanguage=(nextLanguage:Lang)=>{setLang(nextLanguage);onLanguageChange?.(nextLanguage)};
  const refresh=async()=>{setLoading(true);try{const query=new URLSearchParams({category,people:String(people),lat:String(origin.lat),lon:String(origin.lon)});const response=await fetch(`/api/recommendations?${query}`);if(!response.ok)throw new Error("recommendation api");const data=await response.json();setSpots(data.places);setLive(data.meta?.weatherMarine==="live_forecast")}catch{try{const next=await Promise.all(base.map(liveSpot));setSpots(next);setLive(true)}catch{setSpots(base);setLive(false)}}finally{setUpdated(new Intl.DateTimeFormat(lang,{hour:"2-digit",minute:"2-digit"}).format(new Date()));setLoading(false)}};
  const selectOrigin=(id:OriginId)=>{const next=origins.find(x=>x.id===id)!;setOriginId(id);setOrigin({lat:next.lat,lon:next.lon});setGeoState("idle")};
  const useDeviceLocation=()=>{setGeoState("loading");if(!navigator.geolocation){setGeoState("error");return}navigator.geolocation.getCurrentPosition(({coords})=>{setOrigin({lat:coords.latitude,lon:coords.longitude});setGeoState("success")},()=>setGeoState("error"),{enableHighAccuracy:true,timeout:8000,maximumAge:300000})};
  useEffect(()=>{document.documentElement.lang=lang==="zh"?"zh-CN":lang;refresh();const timer=window.setInterval(refresh,300000);return()=>window.clearInterval(timer)},[lang,category,people,origin.lat,origin.lon]);
  useEffect(()=>{const hydrationTask=window.setTimeout(()=>setUnitPreferences(readUnitPreferences()),0);return()=>window.clearTimeout(hydrationTask)},[]);
  useEffect(()=>{try{window.localStorage.setItem(LEGACY_PREFERENCES_KEY,JSON.stringify({people,category,originId,origin}))}catch{}},[people,category,originId,origin]);
  const allRanked=useMemo(()=>spots.map(s=>{const located={...s,distance:distanceKm(origin,s)};return {...located,scores:score(located,people)}}).sort((a,b)=>b.scores.total-a.scores.total),[spots,people,origin]);
  const ranked=useMemo(()=>{const activeKinds=new Set<Kind>(["surf","sup","kayak","yacht","swim"]);return category==="all"?allRanked:allRanked.filter(s=>category==="activity"?s.categories.includes("activity")&&activeKinds.has(s.kind):s.categories.includes(category))},[allRanked,category]);
  const topRecommendations=ranked.slice(0,3); const topIds=new Set(topRecommendations.map(s=>s.id)); const otherActivities=allRanked.filter(s=>!topIds.has(s.id)); const best=ranked[0];
  const du=directionsUi[lang]; const startName=geoState==="success"?lt.device:origins.find(item=>item.id===originId)!.name[lang];
  const routeEstimate=(mode:TravelMode)=>{const factor=mode==="transit"?1.35:mode==="car"?1.2:1.18;const distance=Math.max(.8,best.distance*factor);const minutes=mode==="transit"?Math.max(18,Math.round(distance/24*60+12)):mode==="car"?Math.max(8,Math.round(distance/32*60+5)):Math.max(10,Math.round(distance/4.5*60));return {distance,minutes}}; const selectedRoute=routeEstimate(travelMode); const routeDistance=selectedRoute.distance; const routeMinutes=selectedRoute.minutes;
  const routeSteps=travelMode==="transit"?du.transitSteps:travelMode==="car"?du.carSteps:du.walkSteps; const naverMode=travelMode==="transit"?"transit":travelMode==="car"?"car":"walk"; const naverUrl=`https://map.naver.com/p/directions/${origin.lon},${origin.lat},${encodeURIComponent(startName)},PLACE/${best.lon},${best.lat},${encodeURIComponent(best.name.ko)},PLACE/-/${naverMode}`;
  const sourceGuide=guides[best.id];
  const guide=best.id==="gijang"?{...sourceGuide,items:[{...sourceGuide.items[0],title:L("Haul-net fishing — check status","후릿그물 체험 — 운영 확인","地引き網体験—実施状況を確認","拉网捕鱼体验—请确认运营"),desc:L("The village currently posts a temporary suspension notice. Call before planning this activity.","현재 마을에 일시중단 공지가 있으므로 이 체험을 계획하기 전에 반드시 전화로 재개 여부를 확인하세요.","現在、一時休止のお知らせがあります。計画前に電話で再開状況をご確認ください。","目前村庄发布了暂停通知，计划参加前请务必致电确认是否恢复。")},...sourceGuide.items.slice(1)]}:sourceGuide; const gu=guideUi[lang];
  const reasons=recommendationReasons(best,people,lang);
  const theme=categoryPanel(category,best,guide,lang);
  const categories:Category[]=["all","activity","fishing","relax","kids"];
  const recommendCta=L("See my recommendations","추천 결과 보기","おすすめ結果を見る","查看推荐结果")[lang];
  return <main className={`legacy-view legacy-view-${view}`}>
    <header className="nav"><a className="logo" href="#top"><span>〰</span>{t.name}</a><div className="language">{(["en","ko","ja","zh"] as Lang[]).map(x=><button className={lang===x?"on":""} onClick={()=>selectLanguage(x)} key={x}>{x==="en"?"EN":x==="ko"?"한국어":x==="ja"?"日本語":"中文"}</button>)}</div></header>
    <section className="compare-hero" id="top"><div><p className="overline">BUSAN · 11 COASTAL SPOTS</p><h1>{t.title}<br/><em>{t.accent}</em></h1><p>{t.sub}</p></div><div className="filters"><div className="origin-filter"><span>{lt.origin}</span><div className="origin-actions"><select value={originId} onChange={e=>selectOrigin(e.target.value as OriginId)} aria-label={lt.choose}>{origins.map(x=><option key={x.id} value={x.id}>{x.name[lang]}</option>)}</select><button className={geoState==="success"?"using-device":""} onClick={useDeviceLocation} disabled={geoState==="loading"}>⌖ {geoState==="loading"?lt.locating:lt.device}</button></div>{geoState!=="idle"&&<small className={`geo-message ${geoState}`}>{geoState==="success"?`✓ ${lt.located}`:geoState==="error"?`! ${lt.denied}`:lt.locating}</small>}</div><div className="people-filter"><span>{t.group}</span><div><button onClick={()=>setPeople(Math.max(1,people-1))}>−</button><b>{people}</b><small>{t.people}</small><button onClick={()=>setPeople(Math.min(10,people+1))}>＋</button></div></div><div className="activity-filter"><span>{t.goal}</span><div>{categories.map(item=><button className={category===item?"active":""} onClick={()=>setCategory(item)} key={item}>{t[item]}</button>)}</div></div><button className="home-recommend-cta" onClick={()=>router.push("/recommend")} type="button">{recommendCta}<span aria-hidden="true">→</span></button></div></section>
    <section className="ranking"><div className="rank-top"><div><span>{t.live}</span><h2>{t.best}</h2><p className={live?"feed live":"feed"}>● {live?t.dataLive:t.dataFallback} · {t.updated} {updated||"--:--"}</p></div><button onClick={refresh} disabled={loading}>↻ {loading?t.loading:t.refresh}</button></div>
      <article className="winner"><div className="winner-visual"><span>{best.icon}</span><b>#1 · {best.activity[lang]}</b></div><div className="winner-info"><div className="winner-title"><div><small>{formatDistance(best.distance,unitPreferences.distance)} · {lt.straight}</small><h3>{best.name[lang]}</h3></div><strong>{best.scores.total}<small>/100</small></strong></div><p>{t.recommend}</p><div className="conditions"><span>🌡 {formatTemperature(best.temp,unitPreferences.temperature)}</span><span>🌊 {t.wave} {best.wave.toFixed(1)}m</span><span>💨 {best.wind.toFixed(1)}m/s</span><span>👥 {best.crowd}% {t.estimated}</span></div><div className="win-actions"><a className="primary" href="#why">{t.details} →</a><a href="#directions">{t.route} ↓</a></div></div></article>
      <section className={`theme-panel theme-${category}`} aria-live="polite"><div className="theme-copy"><span>{theme.eyebrow}</span><h2>{theme.title}</h2><p>{theme.intro}</p></div><div className="theme-cards">{theme.cards.map(card=><article key={card.title}><span>{card.icon}</span><div><h3>{card.title}</h3><p>{card.text}</p></div></article>)}</div></section>
      <section className="activity-guide" aria-live="polite"><div className="guide-heading"><div><span>{gu.eyebrow}</span><h2>{gu.title}<br/><em>{best.name[lang]}</em></h2></div><div className="guide-links">{guide.phone&&<a href={`tel:${guide.phone}`}>☎ {gu.call}</a>}<a href={`https://www.google.com/maps/search/?api=1&query=${best.lat},${best.lon}`} target="_blank" rel="noreferrer">⌖ {gu.map}</a></div></div><div className="guide-facts"><div><small>01 · {gu.where}</small><p>{guide.where[lang]}</p></div><div><small>02 · {gu.how}</small><p>{guide.how[lang]}</p></div><div><small>03 · {gu.check}</small><p>{guide.note[lang]}</p></div></div><div className="guide-items">{guide.items.map((item,i)=><article key={item.title.en}><span>{item.icon}</span><small>OPTION {String(i+1).padStart(2,"0")}</small><h3>{item.title[lang]}</h3><p>{item.desc[lang]}</p></article>)}</div><p className="guide-notice">ⓘ {gu.notice}</p></section>
      <section className="directions-panel" id="directions" aria-live="polite"><div className="directions-heading"><div><span>{du.eyebrow}</span><h2>{du.title}<br/><em>{best.name[lang]}</em></h2></div><a className="naver-route" href={naverUrl} target="_blank" rel="noreferrer">✦ {du.open}</a></div><div className="direction-facts"><article><small>01 · {du.from}</small><p>{startName}<br/>→ {best.name[lang]}</p></article><article><small>02 · {du[travelMode]}</small><p>{du.estimate} {routeMinutes} min<br/>{du.distance} {formatDistance(routeDistance,unitPreferences.distance)}</p></article><article><small>03 · {du.flow}</small><p>{routeSteps[0]}</p></article></div><div className="transport-options" role="tablist" aria-label={du.title}>{(["transit","car","walk"] as TravelMode[]).map((mode,index)=>{const estimate=routeEstimate(mode);const steps=mode==="transit"?du.transitSteps:mode==="car"?du.carSteps:du.walkSteps;return <button key={mode} role="tab" aria-selected={travelMode===mode} className={travelMode===mode?"active":""} onClick={()=>setTravelMode(mode)}><span className="transport-icon">{mode==="transit"?"🚌":mode==="car"?"🚗":"🚶"}</span><small>OPTION {String(index+1).padStart(2,"0")}</small><h3>{du[mode]}</h3><strong>{estimate.minutes} min · {formatDistance(estimate.distance,unitPreferences.distance)}</strong><p>{steps[0]}</p></button>})}</div><p className="directions-notice">ⓘ {du.notice}</p></section>
      <div className="list-head featured-list-head"><div><span>{t.results}</span><h2>{t.compare}</h2></div><small>{topRecommendations.length} SPOTS</small></div><div className="result-list featured-results">{topRecommendations.map((s,i)=><article key={s.id} className={s.scores.unsafe?"unsafe":""}><div className="place-rank">{String(i+1).padStart(2,"0")}</div><div className="place-icon">{s.icon}</div><div className="place-main"><small>{s.activity[lang]} · {formatDistance(s.distance,unitPreferences.distance)}</small><h3>{s.name[lang]}</h3><div><span>{t.water} {formatTemperature(s.water,unitPreferences.temperature)}</span><span>{t.wave} {s.wave.toFixed(1)}m</span><span>{t.wind} {s.wind.toFixed(1)}m/s</span><span>{t.crowd} {s.crowd}%</span></div></div><div className="place-score"><b>{s.scores.total}</b><small>{s.scores.unsafe?t.caution:t.safe}</small></div></article>)}</div>
      <div className="list-head secondary-list-head"><div><span>{t.otherResults}</span><h2>{t.otherCompare}</h2></div><small>{otherActivities.length} SPOTS</small></div><div className="result-list other-results">{otherActivities.map(s=><article key={s.id} className={s.scores.unsafe?"unsafe":""}><div className="place-rank available-mark">＋</div><div className="place-icon">{s.icon}</div><div className="place-main"><small>{s.activity[lang]} · {formatDistance(s.distance,unitPreferences.distance)}</small><h3>{s.name[lang]}</h3><div><span>{t.water} {formatTemperature(s.water,unitPreferences.temperature)}</span><span>{t.wave} {s.wave.toFixed(1)}m</span><span>{t.wind} {s.wind.toFixed(1)}m/s</span><span>{t.crowd} {s.crowd}%</span></div></div><div className="availability-badge">{s.scores.unsafe?t.caution:t.available}</div></article>)}</div>
    </section>
    <section className="method" id="why"><h2>{t.why}</h2><div>{reasons.map(reason=><article key={reason.title}><span>{reason.icon}</span><h3>{reason.title}</h3><p>{reason.text}</p></article>)}</div><p>ⓘ {t.crowdNote}</p><small>{t.source}</small></section>
    <footer><a className="logo" href="#top"><span>〰</span>{t.name}</a><p>Busan marine activity comparison for international travelers.</p></footer>
  </main>
}

export default function OceanLogEntryPage() {
  return <OnboardingFlow />;
}
